# Generated by Django 4.2.19 on 2025-03-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('trimester', 'Trimestre'), ('year', 'Année')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('on_time_tasks_count', models.IntegerField(default=0)),
                ('total_tasks_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('on_time_rate', models.FloatField(default=0)),
                ('bonus_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'period', 'period_start', 'period_end')},
            },
        ),
    ]
